name: 'Test'
on:
  pull_request:

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gradle Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/wrapper/dists/**/gradle*.zip
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - uses: actions/checkout@v4
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          
      - run: |
          npm install
      - run: |
          npm run all

  action-test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Gradle Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/wrapper/dists/**/gradle*.zip
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - uses: actions/checkout@v4

      - name: Test Single Module Project in root
        uses: ./
        with:
          use-gradlew: false
          gradle-build-module: |-
            :
          gradle-build-configuration: |-
            compileClasspath
            
      - name: Test Multi Module Project in subfolder
        uses: ./
        with:
          gradle-project-path: |-
            gradle-example
          gradle-build-module: |-
            :app
            :simple-app
            :library-parent-parent
          gradle-build-configuration: |-
            debugCompileClasspath
          gradle-build-configuration-mapping: |-
            :library-child-2|compileClasspath
          sub-module-mode: 'INDIVIDUAL_DEEP'

      - name: Test Multi Module Project in subfolder - Without configuration filter
        uses: ./
        with:
          gradle-project-path: |-
            gradle-example
          gradle-build-module: |-
            :app
          sub-module-mode: 'INDIVIDUAL_DEEP'